#!/bin/bash
#
# ip järgi arvuti kontrollimine
echo -n  "Sisesta IP algus: "
read algus
echo -n "Sisesta IP lõpp: "
read lopp
for ((nr=$algus; nr<=$lopp; nr++))
#for ip in 172.23.13.{$algus..$lopp}
do
	# paneme ip kokku
	 ip=172.23.13.$nr
	# teostame antud ip pingi
	 ping -c 1 $ip > /dev/null # väljund on kustutatud
	# kontrollime pingi käsu tulemuse, kas läks läbi
	 if [ $? -eq 0 ]; then
	# kui $? on 0 - korras
	 	echo "$ip - ok"
	#muidu
	 else
	 	echo "$ip - not"
	 fi
done
