#!/bin/bash
#
# keskonna ja oma muutujate kasutamine
#
# kasutame keskonna muutuja nimega $USER
# tervitame kasutajat
echo "Tere, $USER!"
# kuupäeva väärtuse loomine
#defineerime vastava väärtusega muutuja
kuupaev=`date +'%d. %B'`
# väljastame kuupäeva koos seletusega
echo "Täna on $kuupaev"
#
# kella väärtuste loomine
# defineerime vastava väärtusega muutuja
kell=`date +'%H:%M'`
# väljastame kell koos seletusega
echo "Kell on $kell"
# skripti lõpp
